export const FETCH_BEACHES = "FETCH_BEACHES";
export const FETCH_BEACHES_SUCCESS = "FETCH_BEACHES_SUCCESS";
export const FETCH_BEACHES_FAILED = "FETCH_BEACHES_FAILED";
export const SELECT_CURRENT_BEACH = "SELECT_CURRENT_BEACH";
export const CLEAR_CURRENT_BEACH = "CLEAR_CURRENT_BEACH";
