// REGISTER TYPES
export const REGISTER_USER = "REGISTER_USER";
export const REGISTER_USER_FAILED = "REGISTER_USER_FAILED";
//LOCATION
export const SET_USER_LOCATION = "SET_USER_LOCATION";
export const TOGGLE_LOCATION = "TOGGLE_LOCATION";

// LOGIN TYPES
export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAILED = "LOGIN_USER_FAILED";

// LOGOUT TYPES

export const LOGOUT_USER = "LOGOUT_USER";
export const LOGOUT_USER_FAILED = "LOGOUT_USER_FAILED";
export const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS";

// Add Favorite

export const ADD_FAVORITE = "ADD_FAVORITE";
export const ADD_FAVORITE_SUCCESS = "ADD_FAVORITE_SUCCESS";
export const ADD_FAVORITE_FAILED = "ADD_FAVORITE_FAILED";
